### ISSUE TITLE
Using this as standalone course running on Kaggle

### ISSUE THREAD

**Issue by mr-bjerre** [Kaggle/learntools#141]
Is it possible to use this tool for a learning course that isn't deployed on [Kaggle Learn](https://www.kaggle.com/learn/overview)?

Imagine I want to create my own course on Python and want to share it with some friends. Is that possible? I still want to run the notebooks on Kaggle.

**Comment by dansbecker** [comment]
@mr-bjerre We haven't designed this library for that purpose. There may be a way to hack something together that used parts of this library (using learntools.core). But I don't think you'd find it worth the effort.

It'd be a nice feature if we made this more extensible and better documented to serve outside courses. But we don't have any plans to do that (and I'm sure it won't happen in 2019.)
