### ISSUE TITLE
Import Error in Pandas course

### ISSUE THREAD

**Issue by VitalyAnkh** [Kaggle/learntools#39]
When I took the Pandas course I met an error:
``` python
import pandas as pd
pd.set_option('max_rows', 5)
from learntools.core import binder; binder.bind(globals())
from learntools.pandas.creating_reading_and_writing import *
print("Setup complete.")
```
```
WARNING:root:Ignoring repeated attempt to bind to globals

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-1cf6d6f127c2> in <module>
      2 pd.set_option('max_rows', 5)
      3 from learntools.core import binder; binder.bind(globals())
----> 4 from learntools.pandas.creating_reading_and_writing import *
      5 print("Setup complete.")

ModuleNotFoundError: No module named 'learntools.pandas'
```

**Comment by VitalyAnkh** [comment]
Thank for your reply! 
Yes, I encountered this error on Kaggle Kernels, and I have tried to run the notebook on my local machine and encountered the similar error: `ModuleNotFoundError: No module named 'learntools'`. It's because I haven't installed Kaggle's `learntools` package. But I don't know why this error happens on the kernels. I also refreshed the page several times but this didn't help.
This is the screenshot:
![_ _20181204224534](https://user-images.githubusercontent.com/24508452/49449770-96563080-f816-11e8-9656-34db891b53f5.png)
I have made the notebook public and this is the [link](https://www.kaggle.com/vitalyankh/creating-reading-and-writing-workbook).

**Comment by colinmorris** [comment]
Thanks for sharing the kernel. I poked around and I think I found the issue: you have the GPU flag enabled. When kernels have GPU enabled, they use a different docker image, meaning the set of libraries they have available are different from the ones available on normal kernels. In particular, the GPU image often has older versions of libraries, because it's updated less frequently. If you turn GPU off, this error should go away. But let me know if that doesn't work.

**Comment by colinmorris** [comment]
Glad it worked! I believe the GPU image will be updated on Thursday. That said, with the possible exception of Deep Learning, the courses on Kaggle Learn will generally not benefit from being run on GPU.

**Comment by eds8531** [comment]
Hi, I'm getting the same message trying to run this on my own device and I'm getting the same error. I'm not sure how to turn off the GPU flag from Jupyter Notebooks.

**Comment by koushikromel** [comment]
Hi, I'm getting the same error for this line of python code `pd.set_option('max_rows', 5)`  the error is 

```python
---------------------------------------------------------------------------
OptionError                               Traceback (most recent call last)
Cell In[6], line 2
      1 import pandas as pd
----> 2 pd.set_option('max_rows', 5)
      3 from learntools.core import binder; binder.bind(globals())
      4 from learntools.pandas.creating_reading_and_writing import *

File /opt/conda/lib/python3.10/site-packages/pandas/_config/config.py:261, in CallableDynamicDoc.__call__(self, *args, **kwds)
    260 def __call__(self, *args, **kwds) -> T:
--> 261     return self.__func__(*args, **kwds)

File /opt/conda/lib/python3.10/site-packages/pandas/_config/config.py:156, in _set_option(*args, **kwargs)
    153     raise TypeError(f'_set_option() got an unexpected keyword argument "{kwarg}"')
    155 for k, v in zip(args[::2], args[1::2]):
--> 156     key = _get_single_key(k, silent)
    158     o = _get_registered_option(key)
    159     if o and o.validator:

File /opt/conda/lib/python3.10/site-packages/pandas/_config/config.py:123, in _get_single_key(pat, silent)
    121     raise OptionError(f"No such keys(s): {repr(pat)}")
    122 if len(keys) > 1:
--> 123     raise OptionError("Pattern matched multiple keys")
    124 key = keys[0]
    126 if not silent:

OptionError: Pattern matched multiple keys
```

And it is fixed by changing the set_option method to the related current version of the pandas library for me it worked when i change it to  `pd.options.display.max_rows = 5`

**Comment by DexSwaper** [comment]
> @VitalyAnkh, did you encounter this error on Kaggle Kernels, or were you trying to run the notebook on your local machine? If the problem was on Kernels, could you set your kernel to public and post a link to it? (Or if you'd rather not make it public, you can add me as a collaborator. My username is colinmorris.)
> 
> Also, if this is on kernels, you might want to try just refreshing the page and trying again, in case it's just a transient error.

what if it's on local machine

**Comment by valmetisrinivas** [comment]
@DexSwaper it won't work as the module is designed for Kaggle environment only. Please see the "Purpose: here [https://github.com/Kaggle/learntools/blob/master/README.md](url)
