### ISSUE TITLE
Type Error in Ex 5 of Intro to SQL

### ISSUE THREAD

**Issue by karmasta13** [Kaggle/learntools#438]
1. When I ran the first cell I got the error 
`│ exit code: 128
  ╰─> See above for output.`
  
2. Later in `q_3.check()` , I got 
`TypeError: only size-1 arrays can be converted to Python scalars`

3. `q_4.check()` , I got 
`IndexError: list index out of range`

**Comment by Pennalaine** [comment]
The same thing happened to me, so I can't get full credit for the lesson.

**Comment by karmasta13** [comment]
> 

It has been solved
